### ISSUE TITLE
[BUG] Cannot destructure property 'apiKey' of 'e' as it is null.

### ISSUE THREAD

**Issue by neff1337** [strapi-community/cloudinary-media-library#3]
## 🔍 Steps to Reproduce
1. Install plugin
2. Open strapi
3. Go to settings -> Configuration (Cloudinary plugin)

## 💻 Environment
- Strapi Version: 5.8.1
- Provider Version: 1.0.0
- Node Version: 20.11.1
- OS: Linux

Also, i see this error when open content with Cloudinary custom field 

![Image](https://github.com/user-attachments/assets/c3f1a4ed-2e0e-4027-bd8d-c1d5bd309c2e)

**Comment by cyp3rius** [comment]
Thanks, for reporting. We will investigate that.

**Comment by cyp3rius** [comment]
@neff1337 the fix was released in `v1.0.1-beta.1`, kindly check

**Comment by michintosh** [comment]
Hi! I have the same problem.
I've tried with both of these plugin.ts configurations:
```javascript
'cloudinary-media-library': {
    enabled: true,
    config: {
      data: {
        cloudName: env("CLOUDINARY_CLOUD_NAME"),
        apiKey: env("CLOUDINARY_API_KEY"),
        encryptionKey: env("CLOUDINARY_ENCRYPT_KEY"),
      }
    },
  },
```
and
```javascript
'cloudinary-media-library': {
    enabled: true,
    config: {
        cloudName: env("CLOUDINARY_CLOUD_NAME"),
        apiKey: env("CLOUDINARY_API_KEY"),
        encryptionKey: env("CLOUDINARY_ENCRYPT_KEY"),
    },
  },
```

But I still get the same error as described before:
error: Cannot destructure property 'apiKey' of 'e' as it is null.

I've installed the `1.0.1-beta.1` and I'm using the Strapi v 5.15.1

**Comment by tonymtz** [comment]
I'm having the same issue, using strapi v5.18.0; I tried with 1.0.1-beta.1

**Comment by cyp3rius** [comment]
@michintosh @tonymtz have you tried to use the default way for providing credentials, like via the Settings Page?

**Comment by michintosh** [comment]
Hi @cyp3rius yes I've tried, but as soon ad I try to get to the settings page I get a 500 server error printend on the dashboard, and the error from the logs it's the same, didn't try with the latest 5.18 though

**Comment by cyp3rius** [comment]
I will get the latest and check how it behave and if I'm able to reproduce. Back to you upcoming week.

**Comment by cyp3rius** [comment]
I would say now there is no chance for this not to work. Please check `v1.0.2-beta.1`, besides that, I can't reproduce the issue.

**Comment by Pawnflake** [comment]
even when i try v1.0.2-beta.1
i get when trying to go to the config page
warn: Using dot notation for model config namespaces is deprecated, for example "plugin::myplugin" should be used instead of "plugin.myplugin". Modifying requested path plugin.cloudinary-media-library to plugin::cloudinary-media-library

and it doesnt load just shows error

**Comment by cyp3rius** [comment]
@Pawnflake it's just a warning that does not affect the loading. THe issue must be somewhere else still. Do you have any other suspected errors in browser / node console?

**Comment by Pawnflake** [comment]
im really suprised you dont see this if you just use the latest strapi this plugin will not work the admin config page errors and if you add the custom field to a content type that will also error when managing the content

**Comment by codeninja-rgb** [comment]
I also see this error when I try to use this plugin.

Uncaught TypeError: (0 , import_react_script_hook.default) is not a function or its return value is not iterable

Strapi: v5.22.0
OS: Linux
@strapi-community/cloudinary-media-library: v1.0.2-beta.1

I hope to get the update for this ASAP.

**Comment by cyp3rius** [comment]
@mateusz-kleszcz would you please prioritize this issue investigation?

**Comment by codeninja-rgb** [comment]
I hope these information may help fixing the issues.

1. Config destructure crash
- Error: Cannot destructure property 'apiKey' of 'e' as it is null.
- Cause: Strapi v5 deprecates plugin.cloudinary-media-library dot notation. Access via plugin::cloudinary-media-library is required. The old path may return null, leading to destructure errors.
- Fix: Switch to UID (plugin::cloudinary-media-library) and add a legacy fallback + defensive error messages.

2. Admin build crash
- Error: Uncaught TypeError: (0, import_react_script_hook.default) is not a function or its return value is not iterable
- Cause: react-script-hook is CJS-shaped; Strapi v5 moved to Vite and Vite/ESM bundling sometimes exposes a non-callable default.
- Fix: Import the module with * as RSH and normalize to a callable function.

**Comment by mateusz-kleszcz** [comment]
Hi @TechSolutionKing,

I’ve created a fix for these issues and published it as `v1.0.2-beta.2`. Could you please check if this resolves the problems in both the Settings Panel and the Admin Panel?

I also added a note to the README stating that the `encryptedKey` property is mandatory and must be set via the config file. Please make sure to include it if you haven’t already.

**Comment by codeninja-rgb** [comment]
Hi @mateusz-kleszcz ,

Thank you so much for the new release!
I just tested it and it’s really awesome—I loved it. It’s almost perfect, and I’m sure other users will love it too.

Could I kindly ask for one more favor before finalizing this release?
As you can see in the attached image, when I select a video instead of an image, the preview is still rendered as <img src="...mp4" />. Because of that, the video doesn’t display properly. Would it be possible to fix this so that video files preview correctly?

Thanks again for your great work—I’m really looking forward to seeing the polished release! 🙌

<img width="1309" height="980" alt="Image" src="https://github.com/user-attachments/assets/dd23f814-4e10-49bb-ae38-6fa81b686c62" />

**Comment by mateusz-kleszcz** [comment]
@TechSolutionKing Glad to hear it’s working! I’ll check whether it’s a quick fix — if it is, I’ll do it now. If it turns out to need more work, I’d suggest creating a separate issue for it.
